### ISSUE TITLE
versioning issue

### ISSUE THREAD

**Issue by IzzySoft** [sikelio/plexmanager#59]
I've noticed the APK (here: the arm64 one) at tag `0.0.1-beta` identifies as

    package: name='wtf.plexmanager' versionCode='1003' versionName='1.0'

while `versionName` would be expected to be `0.0.1-beta`, which is a bit confusing. I guess this is due to [these two lines in `build.gradle`](https://github.com/sikelio/plexmanager/blob/main/android/app/build.gradle#L102). Will you update that with upcoming releases? Please especially take care to have `versionCode` increased with each release (the `1` in `build.gradle` is fine for the first one – and the 4-digit ones in the APKs are the ABI-specific ones generated from that, which again is fine; it's just important that new releases always have a higher `versionCode` to be accepted as updates by Android).

Thanks in advance!

**Comment by sikelio** [comment]
https://github.com/sikelio/plexmanager/commit/102b85865796d2ecbef1cb225260f3643f867139 - Updated version in build.gradle

**Comment by IzzySoft** [comment]
PS: if you wish you can [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) then to link there e.g. from your Readme. And I can also offer you the metadata I've set up here (mostly taken from PlayStore with a few minor adjustments) in Fastlane structures (see my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) for reference/guidance) via PR, so you'd be in control of description & graphics (fastlane would be checked whenever a new release was fetched). Just let me know if you want it.

**Comment by sikelio** [comment]
Thanks for the suggest, I need to think about it
I just have so many work currently that I don't have the time to invest me in my personal projects

**Comment by IzzySoft** [comment]
Take your time – and just let me know when you decided. Your project, your pace :smile:
