### ISSUE TITLE
Minimum Plex server version supported.

### ISSUE THREAD

**Issue by afleuryg** [sikelio/plexmanager#76]
**Describe the bug**
There is no "Plex Token" available in older version of Plex. plexmanager can't connect to the plex server if I put a dummy token value.
Just for our pleasure, there are 2 version strings in my Plex server:
1) in Settings-Plex Web-General: Version 4.34.4 
2) in Settings-Settings-General: Version 1.20.3.3437 
Also, my plex server is not claimed (not linked to a plex.tv account).

**To Reproduce**
1. install an older version of Plex
2. try to obtain the token.

**Expected behavior**
Test plex server version. reject the connection if version is below a certain major/minor.

**Screenshots**
no screenshots.

**Smartphone (please complete the following information):**
not really relevant
- Device: Realme 7 pro
- OS: Android 10.0

**Additional context**
Hi, first of all thank you for your work and congrats on this app. Also, sorry, you have just been hit by being published on F-Droid.
So, my plex server is installed on a NAS -in perfect working condition-, and the NAS vendor locks the apps that can be installed. So my plex server is quite old, and can't be updated. And the result is your app, in its current state, can't work with it. Which is ok, I'm just asking that, if it can't be made to work, it at least fails 'nicely'.
My 'bug' is with a lot of unknown:
1) does the absence of this Token pertain to the fact that there is no associated plex.tv account?
2) in which version of plex did the token appear? Plexopedia doesn't talk about it, Plex doesn't give any info. I can just tell that the Web API changed between version 1.20 and the current version.
3) can the plex server version be tested with only the IP address and port of the server?
4) can this token absence be bypassed somehow?

If you need more info (tests, config files, etc...) just ask. If you want to bin the bug or tag it as not reproducible, it's fine with me too.  :-)

**Comment by sikelio** [comment]
Good evening, I will take a look for this issue when I get some time free.
Thank you for your issue :)

**Comment by afleuryg** [comment]
Good evening, just a note about the server version:
When not connected, hitting the http root of plex server (http://$IP:$port/) gives an xml file containing the following value (on my server): version="1.20.3.3437-f1f08d65b"


![Plex root xml](https://github.com/sikelio/plexmanager/assets/82122762/26735fae-a933-490a-b74c-3dd04fcc5671)
[plex_server_base.xml.txt](https://github.com/sikelio/plexmanager/files/11502901/plex_server_base.xml.txt)

**Comment by afleuryg** [comment]
And the solution is the plex.tv account. As soon as it was registered, I got a token available.
Bug closed, just add to the (future) doc that the server needs to be claimed with a Plex.tv account.

**Comment by sikelio** [comment]
Good evening, sorry for my late response.
I will take a look closely for checking if it's necessary to claim a plex server to use the app. I will not close the issue yet :)

**Comment by sikelio** [comment]
Hello,
This feature will probably be added in a quite long time because if I have to support older version of Plex right now, I will not have time for other necessary functionality. It could be possible that one day I'll create an app for older version.
